language: clojure
lein: lein2

before_install:
  - git clone https://github.com/sass/libsass.git
  - cd libsass && git submodule init && git submodule update
  - ./script/ci-install-deps
  - ./script/ci-install-compiler
  - ./script/ci-build-libsass
  - ls -la $PWD
  - ls -la $PWD/libsass/sassc/bin/sassc
  - export PATH=$PATH:$PWD/libsass/sassc/bin/sassc
  - echo $PATH
  - sassc --help

script: lein2 spec

jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8